config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  
  get '/home' => 'pages#home'
  get '/contact' => 'pages#contact'
  get '/about' => 'pages#about'
  get '/help' => 'pages#help'
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<div class="btn-toolbar">
		    <div class="btn-group">
		        <%= link_to "About", about_path, class: "btn btn-default btn-xs" %>
		    </div>
	    </div>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-default">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
        	</button>
			<% logo = image_tag("logo.png", :alt => "TWEETTER", :class => "navbar-brand mnavbar-brand") %>
			<%= link_to logo, root_path %>
		</div>
		<div class="navbar-collapse collapse navbar-inverse-collapse">

			<ul class="nav navbar-nav navbar-right">
	            <li><%= link_to "Home", root_path %></li>
	            <% if signed_in? %>
	            <li><%= link_to "Users", users_path %></li>
				<li><%= link_to "Profile", current_user %></li>
				<li><%= link_to "Settings", edit_user_path(current_user) %></li>
				<% end %>
				<% if signed_in? %>
				<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
				<% else %>
				<li><%= link_to "Sign in", signin_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</header>	

app/views/layouts/_scripts.html.erb
<script>
(function() {
    var $button = $("<div id='source-button' class='btn btn-primary btn-xs'>&lt; &gt;</div>").click(function() {
        var index = $('.bs-component').index($(this).parent());
        $.get(window.location.href, function(data) {
            var html = $(data).find('.bs-component').eq(index).html();
            html = cleanSource(html);
            $("#source-modal pre").text(html);
            $("#source-modal").modal();
        })

    });

    $('.bs-component [data-toggle="popover"]').popover();
    $('.bs-component [data-toggle="tooltip"]').tooltip();

    $(".bs-component").hover(function() {
        $(this).append($button);
        $button.show();
    }, function() {
        $button.hide();
    });

    function cleanSource(html) {
        var lines = html.split(/\n/);

        lines.shift();
        lines.splice(-1, 1);

        var indentSize = lines[0].length - lines[0].trim().length,
            re = new RegExp(" {" + indentSize + "}");

        lines = lines.map(function(line) {
            if (line.match(re)) {
                line = line.substring(indentSize);
            }

            return line;
        });

        lines = lines.join("\n");

        return lines;
    }

    $(".icons-material .icon").each(function() {
        $(this).after("<br><br><code>" + $(this).attr("class").replace("icon ", "") + "</code>");
    });

})();
</script>
<script>
$(function() {
    $.material.init();

    $( ".btn-unfollow" ).hover(
      function() {
        $( this ).removeClass( "btn-primary" );
        $( this ).addClass( "btn-danger" );
        $(this).attr('value', 'Unfollow');
      }, function() {
        $( this ).removeClass( "btn-danger" );
        $( this ).addClass( "btn-primary" );
        $(this).attr('value', 'Following');
      });
});
</script>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<link rel="shortcut icon" href="../favicon.png" type="image/x-icon">
  		<%= render 'layouts/stylesheets' %>
  		<%= javascript_include_tag "application" %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<div class="jumbotron">
				<% flash.each do |key, value| %>
				<div class="<%= flash_class(key) %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</div>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
		<%= render 'layouts/scripts' %>
	</body>
</html>